### ISSUE TITLE
Installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by toaarnio** [sanguinariojoe/pip-openexr#1]
`pip3 install openexr==1.3.5` (and also 1.3.4) fails when trying to build the wheel on Ubuntu 20.04:

```
 OpenEXR.cpp:36:10: fatal error: ImathConfig.h: No such file or directory
     36 | #include <ImathConfig.h>
        |          ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Previous versions are working fine.

**Comment by hq-jiang** [comment]
Same here. Our CI pipeline failed with the same error, it works fine with 1.3.2. And I confirmed that libopenexr-dev is installed.

**Comment by yarovd** [comment]
Same trouble on Debian 10.11.

**Comment by sanguinariojoe** [comment]
Woha! I really messed up here!

I though it will be working both in newer and older OpenEXR versions. Thanks for reporting, I am fixing that!

**Comment by sanguinariojoe** [comment]
@toaarnio @hq-jiang @yarovd Hey guys! I just drop every single query to the Imath headers. Can you give it a shot again please?

**Comment by toaarnio** [comment]
Compilation passes, but linking fails:

```
/usr/bin/ld: cannot find -lOpenEXR
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

**Comment by toaarnio** [comment]
Also, could you remove the broken releases from PyPI? All dependent packages are failing to install at the moment.

**Comment by hq-jiang** [comment]
For me, it fails with the same linking error

**Comment by sanguinariojoe** [comment]
Ubuntu, you are evil!

> Also, could you remove the broken releases from PyPI? All dependent packages are failing to install at the moment.

Done

I will install an Ubuntu VM and test it there

**Comment by sanguinariojoe** [comment]
OK! I made some changes and checked it works in both Manjaro and Ubuntu 20.04. Can you @toaarnio @hq-jiang @yarovd please test it again?

**Comment by hq-jiang** [comment]
Thanks, it seems to be working on my local machine. Still checking out CI.

**Comment by yarovd** [comment]
> 

Yep. It works now, thanks
`Requirement already satisfied: openexr in /usr/local/lib/python2.7/dist-packages (1.3.7)`

**Comment by toaarnio** [comment]
It's working! Thanks!

**Comment by segalinc** [comment]
still failing for bionic and python 3.8

**Comment by sanguinariojoe** [comment]
Hey @segalinc !

It works nice to me. I just needed to install zlib1g-dev before executing pip3

`sudo apt-get install zlib1g-dev`
